version: "3.7"

x-env: &env
  NAME: "addresses"
  NETWORK_NAME: "mainnet"


  # Prefix
  REST_PREFIX: "/api/v1"
  WEBSOCKET_PREFIX: "/ws/v1"
  HEALTH_PREFIX: "/heath"
  METRICS_PREFIX: "/metrics"

  # Endpoints
  MAX_PAGE_SIZE: 100

  # Icon node service
  ICON_NODE_SERVICE_URL: "https://ctz.solidwallet.io/api/v3"

  # CORS
  CORS_ALLOW_ORIGINS: "*"

  # Monitoring
  HEALTH_POLLING_INTERVAL: "60"

  # Logging
  LOG_LEVEL: "DEBUG"
  LOG_TO_FILE: "false"
  LOG_FILE_NAME: "addresses.log"
  LOG_FORMAT: "json"

  # Kafka
  KAFKA_BROKER_URL: "kafka:9092"
  SCHEMA_REGISTRY_URL: "schemaregistry:8081"
  KAFKA_GROUP_ID: "addresses-service"

  # Topics
  CONSUMER_TOPICS: "addresses"
  SCHEMA_NAME_TOPICS: "addresses-ws:addresses"
  SCHEMA_FOLDER_PATH: "/app/schemas/"

  # DB
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "changeme"
  DB_DBNAME: "postgres"
  DB_SSL_MODE: "disable"
  DB_TIMEZONE: "UTC"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_CHANNEL: "addresses"
  REDIS_SENTINEL_CLIENT_MODE: "false"
  REDIS_SENTINEL_CLIENT_MASTER_NAME: "master"


services:
  addresses-api:
    build:
      context: ${ADDRESSES_CONTEXT:-.}
      target: ${ADDRESSES_TARGET:-prod}
      args:
        - SERVICE_NAME=api
    ports:
      - "8000:8000"     # API
      - "8180:8180"     # Health
      - "9400:9400"     # Prometheus
      - "40000:40000"   # Remote Debug
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${ADDRESSES_CONTEXT:-.}/src:/app
    environment:
      <<: *env
      # Ports
      PORT: "8000"
      HEALTH_PORT: "8180"
      METRICS_PORT: "9400"

  addresses-worker:
    build:
      context: ${ADDRESSES_CONTEXT:-.}
      target: ${ADDRESSES_TARGET:-prod}
      args:
        - SERVICE_NAME=worker
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${ADDRESSES_CONTEXT:-.}/src:/app
    environment:
      <<: *env

  addresses-balance-worker:
    build:
      context: ${ADDRESSES_CONTEXT:-.}
      target: ${ADDRESSES_TARGET:-prod}
      args:
        - SERVICE_NAME=worker
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${ADDRESSES_CONTEXT:-.}/src:/app
    environment:
      <<: *env
      ONLY_RUN_BALANCE_ROUTINE: "true"
